import {StyleSheet} from 'react-native';
import {globalColors} from './GlobalColors';

export const StylesHistorial = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    position: 'relative',
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    left: 0,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  headerCard: {
    width: '100%',
    backgroundColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconImages: {width: 24, height: 24},
  iconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 999,
    padding: 8,
    elevation: 2,
  },
  title: {
    marginLeft: 20,
  },
  historialContainer: {
    flex: 1,
    paddingHorizontal: 15,
  },
  card: {
    elevation: 2,
    backgroundColor: 'white',
    marginHorizontal: 15,
    marginVertical: 15,
    paddingVertical: 20,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  cardIcon: {
    width: 50,
    height: 40,
  },
  dateCard: {
    color: '#454545',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  profileCard: {
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 10,
    backgroundColor: 'transparent',
  },
  fotoCard: {
    width: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 999,
    marginLeft: 5,
    marginRight: 15,
  },
  clientCard: {
    color: '#454545',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 3,
  },
  textCard: {
    fontSize: 14,
    color: globalColors.lightGrey,
  },
  puntosContainer: {
    position: 'relative',
    flexDirection: 'row',
    marginBottom: 12,
  },
  puntos: {
    position: 'relative',
    width: 25,
    alignItems: 'center',
  },
  puntosText: {
    position: 'relative',
    flexDirection: 'column',
    marginLeft: 5,
  },
  puntoInicio: {
    width: 20,
    height: 20,
    backgroundColor: '#1b90dc',
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  puntoInicioRelleno: {
    width: 7,
    height: 7,
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
  },
  intentos: {
    width: 15,
    height: 15,
    backgroundColor: '#1b90dc',
    borderRadius: 999,
    marginTop: 2,
  },
  puntoFinal: {
    width: 17,
    height: 17,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#1b90dc',
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  puntoFinalRelleno: {
    width: 9,
    height: 9,
    backgroundColor: '#1b90dc',
    borderRadius: 999,
  },
  rayaDivisoraPuntos: {
    position: 'absolute',
    backgroundColor: '#1b90dc',
    width: 2,
    height: '100%',
    top: 20,
    left: 12,
  },
  puntosCard: {
    fontSize: 16,
    color: globalColors.lightGrey,
  },
  textPuntosCard: {
    fontSize: 16,
    color: '#454545',
  },
  containerEstado: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  estadoCard: {
    color: '#FFFFFF',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#1b90dc',
    backgroundColor: '#1b90dc',
    borderRadius: 15,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  textHoras: {
    fontSize: 16,
    fontWeight: 'bold',
    paddingVertical: 5,
    color: '#454545',
  },
});
